spring:
  profiles:
    active: prod

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://localhost:3306/eventdb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver